### ISSUE TITLE
Ensure only verified users are visible in /users/ route

### ISSUE THREAD

**Issue by cpritcha** [comses/comses.net#273]

**Comment by alee** [comment]
only users who have logged / signed up recently will have an associated `EmailAddress` so this would winnow down the users list considerably. It's not necessarily a bad thing but we should discuss.

The query could be done in raw sql or probably done through EmailAddress, e.g.,  `EmailAddress.objects.filter(verified=True).values_list('user__member_profile', flat=True)`

**Comment by alee** [comment]
not needed for now
