### ISSUE TITLE
add EU compliant cookie accept

### ISSUE THREAD

**Issue by alee** [comses/comses.net#301]
https://www.cookielaw.org/the-cookie-law/

**Comment by alee** [comment]
https://github.com/TyMaszWeb/django-cookie-law

**Comment by alee** [comment]
https://www.google.com/about/company/consentstaging.html

**Comment by cpritcha** [comment]
https://www.eugdpr.org/key-changes.html

**Comment by alee** [comment]
iterate on cookie page content with directorate
