### ISSUE TITLE
Remaining Peer Review Work

### ISSUE THREAD

**Issue by cpritcha** [comses/comses.net#356]
## Editor Feedback

- [x] display private reviewer notes

## Reviewer Feedback

- [ ] ensure that if you submit then and say that it meets standards it must have all check boxes selected
- [ ] create a separate form for saving

## Member Profile Detail Page

- [x] change badge to danger or warning if the reviewer has to do work

## Permissions Testing

- [x] reviewer cannot change completed reviews

## Review Editor Page

- [x] display feedback link more clearly (now it is hidden behind a badge)

## Feedback Creation Model (backlogged)

- [ ] when a reviewer requests feedback create a new feedback object for them and copy over content from previous object. make feedback immutable.

Currently a reviewer can edit only one feedback object

## Documentation

document how the peer review process is supposed to work for the:

- [ ] editor
- [ ] reviewer
- [ ] submitter

**Comment by alee** [comment]
Closing omnibus for now, reopen with any remaining targeted improvements @cpritcha
