### ISSUE TITLE
codebase tags not appearing in edit common metadata vue form

### ISSUE THREAD

**Issue by alee** [comses/comses.net#370]
submitting codebase tags in the initial entry form are not being persisted properly. Steps to reproduce:

1. Create a new Codebase
2. Add some tags and save
3. Edit Common Metadata -> tags are missing

Tags saved in the Edit Common Metadata modal are saved correctly.

**Comment by cpritcha** [comment]
The edit common metadata form has a tags component. Adding or removing tags updates the tags list for the codebases I tried locally. Could you point me to a problematic codebase?
