### ISSUE TITLE
comses 2018 submission form

### ISSUE THREAD

**Issue by alee** [comses/comses.net#375]
Build an authenticated (require logged-in user) intake form for submissions for https://www.comses.net/conference/2018/

Fields to collect: 

1. title
2. abstract
3. video URL
4. (optional) how did you hear about CoMSES 2018?
5. Anything else?

**Comment by MarcoAJanssen** [comment]
Ask a question like:
Hereby I confirm that the length of the video is not more than 12 minutes.

Perhaps: Presenters, since there might be additional people than the person who upload the information being presenters.

the rest looks OK.

**Comment by alee** [comment]
Good point, I thought about having checkboxes for each of the following guidelines that we listed:

- [ ] Video length <= 12 minutes 
- [ ] Presentation is in English
- [ ] Presentation is related to the theme of the conference 
- [ ] Presenter is a CoMSES member at the time of submitting the video (this will be ensured by requiring authenticated submission)
- [ ] Presenter has included a link to their model code and documentation and archived it in the comses model library or other digital repository (recommended)

**Comment by cpritcha** [comment]
- [ ] Video is hosted on youtube

**Comment by alee** [comment]
Are we requiring a youtube upload this time around? I was thinking we'd use youtube-dl (which can capture off a wide variety of platforms) and then re-upload to https://www.youtube.com/user/CoMSESNet/ as needed. But of course it would be less work if they just did that and we added their video to our channel.

**Comment by MarcoAJanssen** [comment]
Hi Allen,


It would be useful to ask them to send us their YouTube URL. If we have time we could move it to the ComSES Net YouTube. I think it is better to ask people to send a URL than that you get all kinds of WeTransfer emails separate from the sign up.


Marco

________________________________

**Comment by alee** [comment]
added URL at /conference/<year>/submit and finalized in 8539fcca2ead7ff33b831c9a4034cd61e953df24

**Comment by alee** [comment]
We've left additional presenters out for the time being on the UI but there is support for it on the backend so we can add more contributors to the presentation manually.
