### ISSUE TITLE
add purpose of code archival and documentation page to comses.net and link to it from catalog

### ISSUE THREAD

**Issue by cpritcha** [comses/comses.net#424]
Why should we share our model code?

**Comment by alee** [comment]
@chyhuang :wave: please let me know when you've got a first draft of this content ready - it doesn't need to be perfect, we just need an initial text blurb and we can always refine later. I'll put it up at www.comses.net/codebases/why-archive or somewhere similar

**Comment by alee** [comment]
tasks remaining:

- [ ] edit archival document, modify DOI / peer review requirements and add relative data paths
- [ ] put on forum.comses.net

**Comment by alee** [comment]
Closing for now, will create static pages later. Links to tutorials have been added to the model ingest page in fa263a176a28465e3fa6d7986ac37f90ca5818c0 and 07e5676e068978e40f788a5b26c0d997d191b82d
