### ISSUE TITLE
Make Release Contributors edit state explicit

### ISSUE THREAD

**Issue by cpritcha** [comses/comses.net#463]
Canceling the edit contributor form takes you back to the edit release contributor state but doesn't provide any visual cues as to why you can't edit any existing release contributors until the cancel button is pressed on the edit release contributor form. There should be some visual cues.

**Comment by alee** [comment]
can we make it so the Cancel button doesn't even display until there's something to Cancel?

**Comment by alee** [comment]
Also, requiring the user to cancel twice seems like bad design. We should just bypass that if possible and get back to being able to edit existing release contributors. 

Basically it only displays once they've entered data in that outer form form that binds contributors + roles together

**Comment by cpritcha** [comment]
can we make it so the Cancel button doesn't even display until there's something to Cancel?

That would be better. I'm looking into setting the state to the list view if the release contributor form is empty (if it's not empty then may still be editing the release contributor).

**Comment by alee** [comment]
closed in a11337f7aab7e3af83512fe1c8c66e4149162b9f (for future reference @cpritcha you autoclose issues by [these keywords](https://help.github.com/en/articles/closing-issues-using-keywords)
