### ISSUE TITLE
add peer review guidance to Request Peer Review in edit codebase release form

### ISSUE THREAD

**Issue by alee** [comses/comses.net#480]
The Request Peer Review modal in https://github.com/comses/comses.net/blob/master/frontend/src/pages/codebase/release/workflow.ts should also display the peer review guidance displayed on release retrieve django page. 

Complicating this is that the current peer review guidance is Django / markdown only (lives in https://github.com/comses/comses.net/tree/master/django/library/templates/library/review/includes) and getting that same text into the frontend app will be tricky without duplicating it. 

Thoughts on how to do this cleanly would be welcome @cpritcha @chrstngyn

**Comment by chrstngyn** [comment]
https://forum.vuejs.org/t/passing-jinja2-data-as-div-attribute/18350
