### ISSUE TITLE
Link to Introduction to Agent Based Modeling dead

### ISSUE THREAD

**Issue by cpritcha** [comses/comses.net#488]
https://cbie.gitbook.io/introduction-to-agent-based-modeling doesn't work.

**Comment by alee** [comment]
It's deliberately dead, as Marco is finalizing a new version of the book at intro2abm.com - where were you seeing the link?

**Comment by cpritcha** [comment]
on Resources > Education

**Comment by alee** [comment]
thanks for catching that, fixed
