### ISSUE TITLE
Website Navigation Rearrangement

### ISSUE THREAD

**Issue by cpritcha** [comses/comses.net#495]
Website layout changes

Rename
- [x] documentation standards -> modeling standards

Rearrange
- [ ] move FAQ from from 'users / FAQ' to 'resources / FAQ'
- [x] remove events from resources
- [ ] add submenus to top level
- [ ] move events under community
- [x] add bibliography link to CoMSES.net (on the computational model library page, a link in resources)
- [x] tutorials in guides to good practice
- [ ] top tabs match sections below

**Comment by cpritcha** [comment]
@alee Create a new sitemap and compare with the old sitemap

**Comment by alee** [comment]
closing, these proposed changes should be supplanted by the more finely grained results from the usability study
