### ISSUE TITLE
make all navigation links inline on landing page

### ISSUE THREAD

**Issue by chrstngyn** [comses/comses.net#530]
layered header makes it hard for the eye to easily glance at the header

- [ ] move the top row of links to be inline with the rest of the navigation items
- [ ] combine sign-in and become a member

![image](https://user-images.githubusercontent.com/8737685/97374536-c3ca7e00-1875-11eb-89b9-fada09d1abe4.png)

-----------------------------------------------------------------------

currently looks like this:

![image](https://user-images.githubusercontent.com/8737685/97344862-8ef30280-1846-11eb-800a-4619c67295cf.png)

**Comment by alee** [comment]
interestingly, data one went for a layered links in their new UI too :shrug: https://www.dataone.org/about/
