### ISSUE TITLE
add feature to collapse/expand info 

### ISSUE THREAD

**Issue by chrstngyn** [comses/comses.net#533]
users should be able to condense and expand information that they wish to use/view. having all of this information display on default can be overwhelming

![image](https://user-images.githubusercontent.com/8737685/97352665-2e68c300-1850-11eb-93f3-9afb8e723b41.png)

**Comment by alee** [comment]
I think the final consensus was to merge all of these into a single gray box? I need to closer look at the final report again though..

**Comment by alee** [comment]
this is done and deployed on staging: https://test.comses.net/codebases/2222/releases/1.1.0/
