### ISSUE TITLE
improve tag filtering in the search functionality

### ISSUE THREAD

**Issue by chrstngyn** [comses/comses.net#535]
- [ ] refactor tag -> keyword
- [ ] show all selected tags
- [ ] when creating or editing search query, enable removing 1 tag alongside clearing all tags
- [ ] save selected tags in the right side bar
- [ ] close menu of tag autocomplete suggestions after a tag is added
- [ ] dynamically increase text field for tags as more tags are added

![image](https://user-images.githubusercontent.com/8737685/97474809-beb70e80-1909-11eb-90bf-919536f9d8e6.png)

--------------------------------------------------

not all selected tags are shown after selecting tags on the right side search bar

![image](https://user-images.githubusercontent.com/8737685/97372961-0d18ce80-1872-11eb-97c5-0097f0186bf0.png)

--------------------------------------------------

- option of “Press enter to select” hides tag word when mouse hovers each tag
- hard to understand “Press enter to remove”. Typically Enter is used to apply something, not remove

![image](https://user-images.githubusercontent.com/8737685/97354077-185c0200-1852-11eb-92fd-a3d54ac875b5.png)

--------------------------------------------------

displaying tags is confusing. e.g. if multiple tags were selected, only one is shown

![image](https://user-images.githubusercontent.com/8737685/97354330-738df480-1852-11eb-84d9-3df161430e99.png)

**Comment by sgfost** [comment]
some of this added in frontend upgrade #652

work continued in >>> comses/planning#20
