### ISSUE TITLE
refine sort by feature 

### ISSUE THREAD

**Issue by chrstngyn** [comses/comses.net#536]
- combination of ascending/descending and "sort by..." filters is confusing
- asc/desc isn't a common way of filtering data so we could just remove it or merge it into the "sort by..." feature  

![image](https://user-images.githubusercontent.com/8737685/97475170-2705f000-190a-11eb-9a4c-02b288952d8a.png)

------------------------------

![image](https://user-images.githubusercontent.com/8737685/97369069-66c8cb00-1869-11eb-9ac8-5e40f5295db1.png)

**Comment by sgfost** [comment]
resolved in vue 3 codebase #644
