### ISSUE TITLE
QR Codes for Release URLs/DOIs/vCards

### ISSUE THREAD

**Issue by cpritcha** [comses/comses.net#578]
A QR code accessible on a codebases release page may make it easier to share a model at conferences or for presentations

https://segno.readthedocs.io/en/latest/web-development.html

**Comment by alee** [comment]
This is a neat idea but Chrome already has this built in:

![image](https://user-images.githubusercontent.com/22534/148487875-9ea2cfe8-76cf-4019-ac41-14a6296b4d9e.png)

and Firefox has similar extensions to do the same.. I think this is something we'll probably backlog for some time.

Hope all's well in Inuvik Calvin!
