### ISSUE TITLE
reorganize community / education sections

### ISSUE THREAD

**Issue by alee** [comses/comses.net#584]
Make education a top level page + navlink e.g., `Home / Education`

Some possibilities:

- [x] Move Education out of Resources tab into its own top level page
- [x] Move Community as a tab of the About page
- [ ] Community should be more laser focused on community things: twitter, conferences, other organizations: OMF, other research groups and partners, open science initiatives, engagement with other researchers. Remove content unrelated to Community

**Comment by chrstngyn** [comment]
more tutorial-focused and focus on materials and resources that are regularly maintained
remove books courses and other resources - less focused on abm
reorganize educational resources around topics as opposed to what type of content

**Comment by alee** [comment]
top level education page should have login guards for subpages (courses, tutorials for certification)

**Comment by alee** [comment]
closing in favor of https://github.com/comses/planning/issues/67
