### ISSUE TITLE
Archiving code of somebody else

### ISSUE THREAD

**Issue by MarcoAJanssen** [comses/comses.net#623]
It is possible somebody who is not the author of the code is archiving the code. But in the "cite this model" the model in comses the submitter is listed as the author of the model. Ideally when people submit they should have the option to submit the code of somebody else and the original authors should be listed as authors in "cite this model". Not a high priority, but with making models FAIR we may get more of those cases (Mohsen experienced such a case).

**Comment by alee** [comment]
This is already possible with Contributors:

https://forum.comses.net/t/archiving-your-model-3-adding-contributors/7379
