### ISSUE TITLE
Elasticsearch Indexing and Permissions

### ISSUE THREAD

**Issue by cpritcha** [comses/comses.net#76]
- should Elasticsearch index private Codebases?
  - if it does index private codebases we need to filter the queries based on the user permissions
  - if it does not index private codebases we will have search queries on postgres as well

**Comment by alee** [comment]
https://www.elastic.co/guide/en/x-pack/current/field-and-document-access-control.html might be overkill

http://stackoverflow.com/questions/35245976/how-to-handle-private-data-in-elastic-search

I'm leaning towards having ES index everything and then we'll do django-guardian filtering on the way out. Is that possible?

**Comment by alee** [comment]
closing, policy is to not index private codebases
